export const GET_GROUP_CHATS_REQUEST = "GET_GROUP_CHATS_REQUEST";
export const GET_GROUP_CHATS_SUCCESS = "GET_GROUP_CHATS_SUCCESS";
export const GET_GROUP_CHATS_FAIL = "GET_GROUP_CHATS_FAIL";

export const GET_FRIENDS_CHATS_REQUEST = "GET_FRIENDS_CHATS_REQUEST";
export const GET_FRIENDS_CHATS_SUCCESS = "GET_FRIENDS_CHATS_SUCCESS";
export const GET_FRIENDS_CHATS_FAIL = "GET_FRIENDS_CHATS_FAIL";

export const GET_USER_FRIENDS_REQUEST = "GET_USER_FRIENDS_REQUEST";
export const GET_USER_FRIENDS_SUCCESS = "GET_USER_FRIENDS_SUCCESS";
export const GET_USER_FRIENDS_FAIL = "GET_USER_FRIENDS_FAIL";

export const CREATE_FRIEND_CHAT_REQUEST = "CREATE_FRIEND_CHAT_REQUEST";
export const CREATE_FRIEND_CHAT_SUCCESS = "CREATE_FRIEND_CHAT_SUCCESS";
export const CREATE_FRIEND_CHAT_FAIL = "CREATE_FRIEND_CHAT_FAIL";

export const DELETE_FRIEND_CHAT_REQUEST = "DELETE_FRIEND_CHAT_REQUEST";
export const DELETE_FRIEND_CHAT_SUCCESS = "DELETE_FRIEND_CHAT_SUCCESS";
export const DELETE_FRIEND_CHAT_FAIL = "DELETE_FRIEND_CHAT_FAIL";

export const CREATE_GROUP_CHAT_REQUEST = "CREATE_GROUP_CHAT_REQUEST";
export const CREATE_GROUP_CHAT_SUCCESS = "CREATE_GROUP_CHAT_SUCCESS";
export const CREATE_GROUP_CHAT_FAIL = "CREATE_GROUP_CHAT_FAIL";

export const DELETE_GROUP_CHAT_REQUEST = "DELETE_GROUP_CHAT_REQUEST";
export const DELETE_GROUP_CHAT_SUCCESS = "DELETE_GROUP_CHAT_SUCCESS";
export const DELETE_GROUP_CHAT_FAIL = "DELETE_GROUP_CHAT_FAIL";

export const UPDATE_GROUP_CHAT_REQUEST = "UPDATE_GROUP_CHAT_REQUEST";
export const UPDATE_GROUP_CHAT_SUCCESS = "UPDATE_GROUP_CHAT_SUCCESS";
export const UPDATE_GROUP_CHAT_FAIL = "UPDATE_GROUP_CHAT_FAIL";

export const SET_CURRENT_CHAT = "SET_CURRENT_CHAT";
